# Generated by Django 5.2 on 2025-05-01 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Роль')),
                ('tabel', models.CharField(max_length=20, verbose_name='Табельный номер')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('departure_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город отправления')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата отправления')),
                ('train', models.CharField(blank=True, max_length=50, null=True, verbose_name='Поезд')),
                ('wagon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вагон')),
                ('path_info', models.TextField(verbose_name='Путь неисправности (JSON)')),
                ('repair_code', models.CharField(max_length=10, verbose_name='Код неисправности')),
                ('fault_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание неисправности')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('urgent', 'Срочная')], default='pending', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('route', models.CharField(blank=True, max_length=255, null=True, verbose_name='Маршрут')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт')),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
                'ordering': ['-created_at'],
            },
        ),
    ]
