# Generated by Django 5.2 on 2025-04-28 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fio', models.CharField(max_length=200, verbose_name='ФИО сотрудника')),
                ('employee_tabel', models.CharField(max_length=50, verbose_name='Табельный номер')),
                ('train_number', models.CharField(max_length=50, verbose_name='Номер поезда')),
                ('wagon_number', models.CharField(max_length=100, verbose_name='Номер вагона')),
                ('category_path', models.TextField(verbose_name='Путь по категориям')),
                ('fault_description', models.CharField(max_length=255, verbose_name='Описание неисправности')),
                ('classification_code', models.CharField(max_length=20, verbose_name='Код классификатора')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('assigned', 'В наряде'), ('done', 'Выполнено'), ('urgent', 'Срочная')], default='new', max_length=10, verbose_name='Статус')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('route', models.CharField(blank=True, max_length=255, null=True, verbose_name='Маршрут')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт')),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
                'ordering': ['-created_at'],
            },
        ),
    ]
